on: [push]
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build graph's SPA
        uses: logseq/publish-spa@main
        with:
          theme-mode: dark

      - name: Add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
          branch: main
          clean: false
